name: CI
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Install Buildozer and required dependencies
      - name: Install Buildozer and dependencies
        run: |
          pip install buildozer
          sudo apt-get update
          sudo apt-get install -y openjdk-8-jdk
          sudo apt-get install -y autoconf
          sudo apt-get install -y libtool
          sudo apt-get install -y automake
          sudo apt-get install -y cmake
          sudo apt-get install -y pkg-config
          sudo apt-get install -y libpng-dev
          sudo apt-get install -y zlib1g-dev
          sudo apt-get install -y libjpeg-dev
          sudo apt-get install -y fonts-dejavu
          sudo apt-get install -y python3-setuptools
          sudo apt-get install -y python3-ply
          sudo apt-get install -y python3-yaml
          sudo apt-get install -y python3-docutils
          sudo apt-get install -y python3-six
          sudo apt-get install -y python3-pillow
          sudo apt-get install -y python3-pip
          sudo apt-get install -y unzip
          sudo apt-get install -y ant
          sudo apt-get install -y rsync
          pip install pyinstaller  # Install PyInstaller
          pip install cython      # Install Cython

      # Set up Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          sdk-platform: 29

      # Install AIDL
      - name: Install AIDL
        run: |
          sdkmanager "build-tools;29.0.3"

      # Build the Android app using Buildozer
      - name: Build with Buildozer
        run: |
          buildozer android debug

      # Upload the APK as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: ./bin/*.apk
